site_name: Master IoT UCM - Prácticas RPI/ANIOT/LSI (25/26)
extra_javascript:
  - https://code.jquery.com/jquery-3.7.1.min.js
  - https://code.jquery.com/jquery-3.6.0.min.js
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
    - admonition
    - tables
    - footnotes
    - pymdownx.arithmatex:
        generic: true
nav:
    - Calendario: index.md
    - RPI-I: 
      - LAB1. Introducción al entorno de desarrollo ESP-IDF: RPI-I/P1/index.md
      - LAB2. WiFi en el ESP32: RPI-I/P2/index.md
      - 'LAB3. WiFi: provisionamiento y ahorro de energía': RPI-I/P3/index.md
      - LAB4. ESP WiFi Mesh: RPI-I/P4/index.md
      - 'LAB5. BLE: servidor GATT': RPI-I/P5/index.md
      - 'LAB6. BLE: cliente GATT': RPI-I/P6/index.md
      - LAB7. BLE Mesh: RPI-I/P7/index.md
      - LAB8. 802.15.4 y Thread: RPI-I/P8/index.md
      - LAB9. 6LoWPAN y simulador Cooja: RPI-I/P9/index.md
      - LAB10. LoRa y LoRaWan: RPI-I/P10/index.md
    - RPI-II: 
      - Práctica 1 (I): RPI-II/P1_I/index.md
      - Práctica 1 (II): RPI-II/P1_III/index.md
      - Práctica 2: RPI-II/P2/index.md
      - Práctica 3: RPI-II/P3/index.md
      - Práctica 4: RPI-II/P4/index.md
      - Práctica 5 (I): RPI-II/P5/index.md
      - Práctica 5 (II): RPI-II/P5_II/index.md
      - Práctica 6: RPI-II/P6/index.md
      - Práctica 7: RPI-II/P7/index.md
      - Práctica 8: RPI-II/P8/index.md
    - ANIOT: 
      - Práctica 1: ANIOT/P1/index.md
      - Práctica 1b: ANIOT/P1b/index.md
      - Práctica 2: ANIOT/P2/index.md
      - Práctica 3: ANIOT/P3/index.md
      - Práctica 4: ANIOT/P4/index.md
      - Práctica 5: ANIOT/P5/index.md
      - Práctica 6: ANIOT/P6/index.md
      - Práctica 7: ANIOT/P7/index.md
      - Práctica 7 (adicional): ANIOT/P7/index2.md
      - Práctica 8: ANIOT/P8/index.md
    - LSI:
      - Práctica 0: LSI/Lab0/index.md
      - Práctica 1: LSI/Lab1/index.md
      - Práctica 2: LSI/Lab2/index.md
      - Práctica 3: LSI/Lab3/index.md
      - Práctica 4: LSI/Lab4/index.md
      - Práctica 5: LSI/Lab5/index.md
      - Práctica 6: LSI/Lab6/index.md
